version: '3'
services:
  app:
    restart: always
    build: .
    depends_on:
      - postgres
    environment:
      - .env
    ports:
      - '3000:3000'
    command: yarn start:dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: meetup_database
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: root
    volumes:
      - ./src/db/queries/init.sql:/docker-entrypoint-initdb.d/init.sql
